# Generated by Django 4.2.1 on 2023-07-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ninjauser_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjauser',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('inplay', 'In Play')], default='offline', max_length=10),
            preserve_default=False,
        ),
    ]
